### PR TITLE
Improve performance by removing unneeded work

### PR DESCRIPTION
**Pull request by ericlaw1979**
- Don't recompute score for inactive tabs.
- Don't recompute score when a tab's url hasn't update

### CODE REVIEW

**Comment by ericlaw1979** [comment]
Hrm. While this generally improves performance *dramatically*, it looks like we need a bit more subtlety around the `onUpdated` handler. If you're on a page and you refresh it, it appears that somehow the browser is setting the icon back to the default_icon (despite making no calls to the extension's `setBrowserActionAndIcon` function). The code in the PR fails in this specific case because `changeInfo.url` is falsey and thus we never call `setBrowserActionAndIcon` to restore the proper color.

**Comment by livvielin** [comment]
> Hrm. While this generally improves performance _dramatically_, it looks like we need a bit more subtlety around the `onUpdated` handler. If you're on a page and you refresh it, it appears that somehow the browser is setting the icon back to the default_icon (despite making no calls to the extension's `setBrowserActionAndIcon` function). The code in the PR fails in this specific case because `changeInfo.url` is falsey and thus we never call `setBrowserActionAndIcon` to restore the proper color.

Oh hmm, missed that edge case there. Need to give this some thought.

**Comment by livvielin** [comment]
Would it be possible to store just the flag color and number of alerts on the active tab, then set the flag and badge based on these values in the case of a refresh (i.e. !changeInfo.url)?

**Comment by ericlaw1979** [comment]
Broadly, speaking, yes, caching the Alert State using the tab's FQDN would improve performance, but we'd have to maintain that cache somewhere, handle expiration, etc. We might _need_ to do that in the future if the score calculations get more expensive to compute (history check seems like it's already probably costly), but it's non-trivial complexity.

I think we we can get the vast majority of the performance benefit by limiting scoring updates to active tabs whose URL or loading status changes. This should resolve the refresh case even if it means that we don't eliminate _all_ of the redundant rescoring.

**Comment by livvielin** [comment]
SGTM, thanks! I'll merge this change.

**Pull request merged**
